import React from 'react';
import {
  Flex,
    Box,
      Image,
        Badge,
          useColorModeValue,
            Icon,
              Tooltip,
              } from 'konsta-ui';
              import { BsStar, BsStarFill, BsStarHalf } from 'react-icons/bs';
              import { FiShoppingCart } from 'react-icons/fi';

              const products = [
                {
                    isNew: true,
                        imageURL:
                              'https://images.unsplash.com/photo-1572635196237-14b3f281503f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=4600&q=80',
                                  name: 'Wayfarer Classic',
                                      price: 4.5,
                                          rating: 4.2,
                                              numReviews: 34,
                                                },
                                                  // Add more products here
                                                  ];

                                                  function Rating({ rating, numReviews }) {
                                                    return (
                                                        <Box display="flex" alignItems="center">
                                                              {Array(5)
                                                                      .fill('')
                                                                              .map((_, i) => {
                                                                                        const roundedRating = Math.round(rating * 2) / 2;
                                                                                                  if (roundedRating - i >= 1) {
                                                                                                              return (
                                                                                                                            <BsStarFill
                                                                                                                                            key={i}
                                                                                                                                                            style={{ marginLeft: '1' }}
                                                                                                                                                                            color={i < rating ? 'teal' : 'gray'}
                                                                                                                                                                                          />
                                                                                                                                                                                                      );
                                                                                                                                                                                                                }
                                                                                                                                                                                                                          if (roundedRating - i === 0.5) {
                                                                                                                                                                                                                                      return <BsStarHalf key={i} style={{ marginLeft: '1' }} />;
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                          return <BsStar key={i} style={{ marginLeft: '1' }} />;
                                                                                                                                                                                                                                                                  })}
                                                                                                                                                                                                                                                                        <Box as="span" ml="2" color="gray" fontSize="sm">
                                                                                                                                                                                                                                                                                {numReviews} review{numReviews > 1 && 's'}
                                                                                                                                                                                                                                                                                      </Box>
                                                                                                                                                                                                                                                                                          </Box>
                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                            function Product({ product }) {
                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                  <Box
                                                                                                                                                                                                                                                                                                        bg={useColorModeValue('white', 'gray')}
                                                                                                                                                                                                                                                                                                              maxW="sm"
                                                                                                                                                                                                                                                                                                                    borderWidth="1px"
                                                                                                                                                                                                                                                                                                                          rounded="lg"
                                                                                                                                                                                                                                                                                                                                shadow="lg"
                                                                                                                                                                                                                                                                                                                                      position="relative"
                                                                                                                                                                                                                                                                                                                                            margin="1rem"
                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                      {product.isNew && (
                                                                                                                                                                                                                                                                                                                                                              <Box
                                                                                                                                                                                                                                                                                                                                                                        position="absolute"
                                                                                                                                                                                                                                                                                                                                                                                  top="2"
                                                                                                                                                                                                                                                                                                                                                                                            right="2"
                                                                                                                                                                                                                                                                                                                                                                                                      bg="red"
                                                                                                                                                                                                                                                                                                                                                                                                                borderRadius="full"
                                                                                                                                                                                                                                                                                                                                                                                                                          width="10px"
                                                                                                                                                                                                                                                                                                                                                                                                                                    height="10px"
                                                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Image src={product.imageURL} alt={`Picture of ${product.name}`} roundedTop="lg" />

                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Box p="6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Box display="flex" alignItems="baseline">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {product.isNew && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Badge rounded="full" px="2" fontSize="0.8em" colorScheme="red">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          New
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Badge>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Flex mt="1" justifyContent="space-between" alignContent="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Box fontSize="2xl" fontWeight="semibold" as="h4" lineHeight="tight" isTruncated>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Tooltip
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      label="Add to cart"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bg="white"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              placement={'top'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color={'gray'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fontSize={'1.2em'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Box as="a" href="#" display="flex">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Icon as={FiShoppingCart} h={7} w={7} alignSelf={'center'} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Tooltip>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Flex>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Flex justifyContent="space-between" alignContent="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Rating rating={product.rating} numReviews={product.numReviews} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Box fontSize="2xl" color={useColorModeValue('gray', 'white')}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Box as="span" color={'gray'} fontSize="lg">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              £
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {product.price.toFixed(2)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </Flex>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Box>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    function Index() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <Flex direction="column" alignItems="center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {products.map((product, index) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Product key={index} product={product} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Flex>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    export default Index;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    